# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e1567a0eda033a88e0d11b327169f340259d86acb225f707fb6e0ccebe7316ddb8ca1adc53fb50f6daeb0418648df45d473eeebf4690c0d62b25c0acf5fa78

test:
  secret_key_base: abdeb4c7de061be78519828a5a5a9d79387a8e84b85e49eda8aff8ba8ba8f7b12912575b7d9b5c64d7dccf8087403a3b7509e71cfe5d5c9958a3b22512f1b4bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
